# Generated by Django 3.1 on 2022-12-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
                ('alamat', models.TextField()),
                ('tgl_lahir', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
